---
- name: create agent config directory
  sudo: yes
  file: path=/etc/dataloop state=directory

- name: create agent log directory
  sudo: yes
  file: path=/var/log/dataloop state=directory

- name: create agent plugins directory
  sudo: yes
  file: path=/opt/dataloop/plugins state=directory

- name: create agent rpc directory
  sudo: yes
  file: path=/opt/dataloop/plugins/rpc state=directory

- name: download the latest dataloop-lin-agent binary
  sudo: yes
  get_url: url=https://download.dataloop.io/linux/latest/dataloop-lin-agent.x64 dest=/usr/local/bin/dataloop-lin-agent mode=0755

- name: setup init script
  sudo: yes
  template: src=dataloop-agent.tpl dest=/etc/init.d/dataloop-agent mode=0755
  notify: restart dataloop-agent
